export const DEFAULT_CONFIG = {
  timezone: 'America/Argentina/Buenos_Aires',
  locale: 'es-AR',
  accent: '#7FE9DC',
  showSeconds: true,
  showAnalog: true,
  showDate: true,
  header: '',
  alerts: [
    {
      id: 'a-1',
      label: 'Entrada',
      enabled: true,
      time: '08:30',
      days: [1, 2, 3, 4, 5],
      durationSec: 20,
      blink: true,
      takeover: true,
      message: 'ENTRADA',
      color: '#7FE9DC',
      sound: true,
      pattern: 'chime',
      volume: 0.7,
    },
    {
      id: 'a-2',
      label: 'Almuerzo',
      enabled: true,
      time: '12:00',
      days: [1, 2, 3, 4, 5],
      durationSec: 20,
      blink: true,
      takeover: true,
      message: 'ALMUERZO',
      color: '#F2A93B',
      sound: true,
      pattern: 'beep',
      volume: 0.7,
    },
    {
      id: 'a-3',
      label: 'Salida',
      enabled: true,
      time: '20:47',
      days: [1, 2, 3, 4, 5],
      durationSec: 30,
      blink: true,
      takeover: true,
      message: 'SALIDA',
      color: '#FF4D3D',
      sound: true,
      pattern: 'beep',
      volume: 0.7,
    },
  ],
};
