export const DEFAULT_CONFIG = {
  timezone: 'America/Argentina/Buenos_Aires',
  locale: 'es-AR',
  accent: '#7FE9DC',
  showSeconds: true,
  showAnalog: true,
  showDate: true,
  header: '',
  alerts: [
    {
      id: 'a-1',
      label: 'Apertura',
      enabled: true,
      time: '08:30',
      days: [1, 2, 3, 4, 5],
      durationSec: 20,
      blink: true,
      takeover: false,
      message: 'BUEN TURNO',
      color: '#7FE9DC',
      sound: true,
      pattern: 'chime',
      volume: 0.7,
    },
    {
      id: 'a-2',
      label: 'Corte de mediodía',
      enabled: true,
      time: '12:00',
      days: [1, 2, 3, 4, 5],
      durationSec: 20,
      blink: true,
      takeover: false,
      message: '',
      color: '#F2A93B',
      sound: true,
      pattern: 'beep',
      volume: 0.7,
    },
    {
      id: 'a-3',
      label: 'Cierre de sala',
      enabled: true,
      time: '20:47',
      days: [1, 2, 3, 4, 5],
      durationSec: 30,
      blink: true,
      takeover: false,
      message: 'CIERRE EN 10 MINUTOS',
      color: '#FF4D3D',
      sound: true,
      pattern: 'beep',
      volume: 0.7,
    },
  ],
};
